### PR TITLE
Add readme to proteomic-data (1/N)

### PR DESCRIPTION
**Pull request by zzgeng**
Add `README.md` for proteomic-data module.

https://github.com/d3b-center/hope-cohort-analysis/issues/59

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
Can you please add a description of the input and output files here - maybe @JosephDybas can help inform?

**Review by jharenza — APPROVED** [review]
i will approve but also want @JosephDybas to inform.

**Review by JosephDybas — COMMENTED** [review]
These look good. If appropriate in this file, I would suggest adding information about the data explaining that they are abundance values that are log2 transformed, normalized across samples, and include imputed values. Or will there be a separate description of the methods that lead to the processed data that are in these files?

**Comment by jharenza** [comment]
> These look good. If appropriate in this file, I would suggest adding information about the data explaining that they are abundance values that are log2 transformed, normalized across samples, and include imputed values. Or will there be a separate description of the methods that lead to the processed data that are in these files?

@JosephDybas can you please make these exact suggestions since you know the data?

**Pull request merged**
