### PR TITLE
Annotation file for data availability plot

### PR DESCRIPTION
**Pull request by komalsrathi**
Based on slack request from @mkoptyra the file used for data availability plot is needed by Nicole and Pei. This PR writes the respective file out.

### CODE REVIEW

**Comment by komalsrathi** [comment]
Same for this, could this be reviewed and merged if possible?

**Comment by jharenza** [comment]
>root@XXX:/home/rstudio/hope-cohort-analysis/analyses/data-availability# Rscript --vanilla 03-clinical_data_availability_age_continuous.R
Error: package or namespace load failed for ‘ComplexHeatmap’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘circlize’ 0.4.9 is being loaded, but >= 0.4.14 is required
Execution halted

It looks like we need a new version of circlize in the docker image - have you been running in the image or outside of it. I will update it when I update the docker image.

Also, should there be two 03 scripts in this module? If so, can you update the run script and README in this PR to add the second one `03-clinical_data_availability_age_continuous_cns_region.R`

**Review by jharenza — APPROVED** [review]
This generates the proper output- I will take care of circlize in a new PR. Can you just update the readme/run script to add the second 03 file, then feel free to merge?

**Comment by komalsrathi** [comment]
The two scripts have the same numerical prefix because they are not sequential but rather can be run at the same time.

**Comment by komalsrathi** [comment]
I removed that script because it is not being used/not required for the manuscript.

**Pull request merged**
