### PR TITLE
update dockerfile to R4.4, reorg

### LINKED ISSUE #103: Update dockerfile to use R 4.4/BioC 3.19
Due to security issues, Update dockerfile to use R 4.4/BioC 3.19

### PR DESCRIPTION
**Pull request by jharenza**
This PR updates the docker image.
Closes #103 

pull using `docker pull pgc-images.sbgenomics.com/d3b-bixu/d3b_hope_analysis:latest`

### CODE REVIEW

**Review by komalsrathi — APPROVED** [review]

**Comment by komalsrathi** [comment]
I added `ggforce` and `GSVA` to the Dockerfile. How can I test if it is working?

**Comment by komalsrathi** [comment]
Added `WGCNA`, `DGCA`, `NOISeq`, `sva` packages required for `oncoplots` module.

**Comment by komalsrathi** [comment]
Seems like the build was successfully but I am unable to push it back:

```
# build 
(base) ➜  d3b-hope-cohort-analysis git:(rokita/docker-r4.4) ✗ docker build --platform=linux/amd64 -t pgc-images.sbgenomics.com/d3b-bixu/d3b_hope_analysis:latest .

[+] Building 1606.0s (25/25) FINISHED                                                                                              
 => [internal] load build definition from Dockerfile                                                                          0.0s
 => => transferring dockerfile: 2.80kB                                                                                        0.0s
 => [internal] load metadata for docker.io/rocker/tidyverse:4.4.0                                                             0.3s
 => [internal] load .dockerignore                                                                                             0.0s
 => => transferring context: 2B                                                                                               0.0s
 => [ 1/20] FROM docker.io/rocker/tidyverse:4.4.0@sha256:3e72037abda2a32d86021bbe5725e727f2c02233e4072557bc70c1e890e3471b     0.0s
 => [internal] load build context                                                                                             0.0s
 => => transferring context: 2.79kB                                                                                           0.0s
 => CACHED [ 2/20] WORKDIR /rocker-build/                                                                                     0.0s
 => CACHED [ 3/20] RUN apt-get update                                                                                         0.0s
 => CACHED [ 4/20] RUN apt-get install -y --no-install-recommends apt-utils dialog                                            0.0s
 => CACHED [ 5/20] RUN apt-get install -y --no-install-recommends   libxt6   bzip2   libmagick++-dev                          0.0s
 => CACHED [ 6/20] RUN apt update && apt install -y zlib1g-dev  libncurses5-dev  libbz2-dev  liblzma-dev  libcurl4-openssl-d  0.0s
 => CACHED [ 7/20] RUN R -e "install.packages('BiocManager', dependencies=TRUE)"                                              0.0s
 => CACHED [ 8/20] RUN R -e "BiocManager::install(version = '3.19')"                                                          0.0s
 => CACHED [ 9/20] RUN R -e 'BiocManager::install(c(  "Biobase",  "BiocManager",     "broom",  "circlize",     "ComplexHeatm  0.0s
 => CACHED [10/20] RUN R -e "remotes::install_github('d3b-center/annoFusedata', ref = '321bc4f6db6e9a21358f0d09297142f6029ac  0.0s
 => CACHED [11/20] RUN R -e "remotes::install_github('clauswilke/colorblindr', ref = '90d64f8fc50bee7060be577f180ae019a9bbbb  0.0s
 => [12/20] RUN R -e "devtools::install_github('andymckenzie/DGCA', dependencies = TRUE)"                                   199.0s
 => [13/20] RUN apt-get update                                                                                               10.6s
 => [14/20] RUN apt-get -y --no-install-recommends install     python3-pip  python3-dev                                      21.9s 
 => [15/20] RUN ln -s /usr/bin/python3 /usr/bin/python                                                                        0.2s 
 => [16/20] RUN python3 -m pip install --upgrade pip                                                                          8.2s
 => [17/20] RUN pip3 install     "Cython==0.29.15"     "setuptools==46.3.0"     "six==1.14.0"     "wheel==0.34.2"     "num  132.7s
 => [18/20] RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools-2.28.0.tar.gz &&     tar -zxvf  1222.8s
 => [19/20] RUN wget https://github.com/bedops/bedops/releases/download/v2.4.37/bedops_linux_x86_64-v2.4.37.tar.bz2 &&     t  7.9s
 => [20/20] ADD Dockerfile .                                                                                                  0.0s
 => exporting to image                                                                                                        2.3s
 => => exporting layers                                                                                                       2.3s
 => => writing image sha256:17133f75f0c1cdd8e3e12a85e597f5642f99b3c4d7defdb67f0dba9422769e34                                  0.0s
 => => naming to pgc-images.sbgenomics.com/d3b-bixu/d3b_hope_analysis:latest                                                  0.0s


# login
(base) ➜  d3b-hope-cohort-analysis git:(rokita/docker-r4.4) docker login -u rathik
Password: 
Login Succeeded

# push
(base) ➜  d3b-hope-cohort-analysis git:(rokita/docker-r4.4) docker push pgc-images.sbgenomics.com/d3b-bixu/d3b_hope_analysis:latest 
The push refers to repository [pgc-images.sbgenomics.com/d3b-bixu/d3b_hope_analysis]
ce2c9201c712: Preparing 
ed004bd7bbbd: Preparing 
6aba628dbd1f: Preparing 
f75e52d2381e: Preparing 
dfc5556f05e0: Preparing 
afabbc7ae5a1: Waiting 
d4dca092f84c: Waiting 
9ca7c3d68b00: Waiting 
7215263e2940: Waiting 
5231492d46b9: Waiting 
8233cc31116b: Waiting 
ac8b4c1c58a5: Waiting 
4cb11e9307d5: Waiting 
f5de03c35455: Waiting 
c04a1bf9508b: Waiting 
e935ffc4992a: Waiting 
336f79fe8293: Waiting 
df8beafe2f9a: Waiting 
5166f66a9e36: Waiting 
f3ad2f877ea5: Waiting 
97b1240e5898: Waiting 
4ee61cc03a1b: Waiting 
35fc7b5bd33f: Waiting 
d4a6f91888e5: Waiting 
042bffa43a9d: Waiting 
a98c2a691afc: Waiting 
36046643b3a5: Waiting 
3ad1a1337d67: Waiting 
4021ef4cbcfd: Waiting 
77bf3a6597e3: Waiting 
8fcd48def63b: Waiting 
ad01e26ce07f: Waiting 
ebb3249303fd: Waiting 
a70ce9daeb71: Waiting 
a9735cb448cd: Waiting 
90f274531fe2: Waiting 
34001437ccad: Waiting 
676d9581ed96: Waiting 
0b9c994b0484: Waiting 
denied: requested access to the resource is denied
```

**Comment by komalsrathi** [comment]
Image was built and pushed. Tested relevant modules by re-running them on Docker. All ran without issues.

**Comment by komalsrathi** [comment]
@jharenza regarding your email for DGCA: I was able to successfully install it using the Dockerfile. Okay see my commits. Thanks.

**Review by naqvia — APPROVED** [review]
Installed libraries run as intended! Good work!

**Pull request merged**
