### PR TITLE
Reform proteomic output data (2/N)

### PR DESCRIPTION
**Pull request by zzgeng**
- [x] Remove `OldSymbol` column
- [ ] Remove `--explode-record` flag
- [x] Rename the output files.

### CODE REVIEW

**Review by JosephDybas — CHANGES_REQUESTED** [review]
I ran this on EC2 in a Docker container. The R script worked properly. However, I got the following error in the liftover script.

Error updating gene MUM1. HGNC has multiple options: ['IRF4', 'PWWP3A']. To output all potential new genes use --explode_records flag.

Perhaps the removal of the -explote_records flag isn't working as intended?

**Comment by zzgeng** [comment]
I added Note column to the proteomic liftover files. The genes that are derived from the same gene symbol after liftover are labeled with the previous gene symbol. Others labels as `non-duplicated`. Also, should we update the input of proteomic files to the 6.0 version?

**Comment by jharenza** [comment]
hi @zzgeng can you merge master into this? I am seeing infinity file changes, taking a while to load, but don't think we should have that many. thanks

**Review by jharenza — APPROVED** [review]

**Review by JosephDybas — APPROVED** [review]
Looks good to me. Thanks!

**Review by jharenza — COMMENTED** [review]
hi @zzgeng can you make sure the column names between phospho and proteomic files we are using are consistent? and are we using the following:
```
Hope_phosphosite_imputed_data_ischemia_removed_motif.tsv
Hope_proteome_imputed_data.tsv
```
?

I request we update names to:
```
hope-protein-imputed-phospho-expression.tsv
hope-protein-imputed-prot-expression.tsv
```

**Review by JosephDybas — APPROVED** [review]
Column names and file name changes look good to me. Thanks!

**Pull request merged**
